/*
* Copyright (c) 2000-2015 Samsung Electronics Co., Ltd All Rights Reserved
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*/


#ifndef _VIDEO_STRING_DEFINE_
#define  _VIDEO_STRING_DEFINE_


#include <app.h>


#define MP_SYS_STRING								"sys_string"
#define VIDEOS_STRING								"videos"

#define VIDEOS_GET_STR(x)							dgettext(VIDEOS_STRING, x)
#define VIDEOS_GET_STR_FMT(x)						_(dgettext(VIDEOS_STRING, x))

/*--------------------------------------------String Define---------------------------------------------------*/

/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//	Title, System
/////////////////////////////////////////////////////////////////////////////////////////////////////////////
#define VIDEOS_TITLE_VIDEO									VIDEOS_GET_STR("IDS_VIDEO_OPT_VIDEOS")
#define VIDEOS_TITLE_VIDEO_PLAYER							(dgettext(MP_SYS_STRING, "IDS_COM_BODY_VIDEO_PLAYER"))
#define VIDEOS_ALERT_LOW_BATTERY							(dgettext(MP_SYS_STRING, "IDS_COM_BODY_LOW_BATTERY"))


/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//	Popup
/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//	Common	//
#define VIDEOS_COMMON_BUTTON_YES_IDS					("IDS_COM_SK_YES")
#define VIDEOS_COMMON_BUTTON_NO_IDS						("IDS_COM_SK_NO")
#define VIDEOS_COMMON_BUTTON_OK							(dgettext(MP_SYS_STRING, "IDS_COM_SK_OK"))
#define VIDEOS_COMMON_BUTTON_OK_IDS						("IDS_COM_SK_OK")
#define VIDEOS_COMMON_BUTTON_CANCEL						VIDEOS_GET_STR("IDS_VIDEO_SK_CANCEL_ABB")
#define VIDEOS_COMMON_BUTTON_CANCEL_IDS					("IDS_CLOCK_BUTTON_CANCEL")
#define VIDEOS_COMMON_BUTTON_CLOSE_IDS					("IDS_COM_BODY_CLOSE")
#define VIDEOS_COMMON_HEADER_ERROR						(dgettext(MP_SYS_STRING, "IDS_COM_POP_ERROR"))
#define VIDEOS_COMMON_MSG_DONT_ASK_AGAIN_IDS			("IDS_MUSIC_BUTTON_DONT_ASK_AGAIN")
#define VIDEOS_COMMON_BUTTON_RENAME_IDS					("IDS_VIDEO_OPT_RENAME")

//	Context popup	//
#define VIDEOS_CTXPOP_MENU_DOWNLOAD						VIDEOS_GET_STR("IDS_VIDEO_BUTTON_DOWNLOAD")
#define VIDEOS_CTXPOP_MENU_DOWNLOAD_IDS				("IDS_VIDEO_BUTTON_DOWNLOAD")
#define VIDEOS_CTXPOP_MENU_SEARCH						VIDEOS_GET_STR("IDS_VIDEO_OPT_SEARCH")
#define VIDEOS_CTXPOP_MENU_SEARCH_IDS					("IDS_VIDEO_OPT_SEARCH")
#define VIDEOS_CTXPOP_MENU_SHARE							VIDEOS_GET_STR("IDS_VIDEO_OPT_SHARE")
#define VIDEOS_CTXPOP_MENU_SHARE_IDS						("IDS_VIDEO_OPT_SHARE")
#define VIDEOS_CTXPOP_MENU_DELETE						VIDEOS_GET_STR("IDS_VIDEO_BUTTON_DELETE")
#define VIDEOS_CTXPOP_MENU_DELETE_IDS					("IDS_VIDEO_BUTTON_DELETE")
#define VIDEOS_CTXPOP_MENU_VIEW_AS						VIDEOS_GET_STR("IDS_VIDEO_OPT_VIEW_AS")
#define VIDEOS_CTXPOP_MENU_VIEW_AS_IDS					("IDS_VIDEO_OPT_VIEW_AS")
#define VIDEOS_CTXPOP_MENU_SORT_BY						VIDEOS_GET_STR("IDS_VIDEO_OPT_SORT_BY")
#define VIDEOS_CTXPOP_MENU_SORT_BY_IDS					("IDS_VIDEO_OPT_SORT_BY")
#define VIDEOS_CTXPOP_MENU_RENAME						VIDEOS_GET_STR("IDS_VIDEO_OPT_RENAME")
#define VIDEOS_CTXPOP_MENU_RENAME_IDS					("IDS_VIDEO_OPT_RENAME")
#define VIDEOS_CTXPOP_MENU_DETAILS						VIDEOS_GET_STR("IDS_VIDEO_OPT_DETAILS")
#define VIDEOS_CTXPOP_MENU_DETAILS_IDS					("IDS_VIDEO_OPT_DETAILS")
#define VIDEOS_CTXPOP_MENU_ADD_TO_HOME					VIDEOS_GET_STR("IDS_VIDEO_OPT_ADD_TO_HOME_SCREEN")
#define VIDEOS_CTXPOP_MENU_CONTENT_TO_DISPLAY			VIDEOS_GET_STR("IDS_VIDEO_OPT_CONTENT_TO_DISPLAY_ABB")
#define VIDEOS_CTXPOP_MENU_CONTENT_TO_DISPLAY_IDS		("IDS_VIDEO_OPT_CONTENT_TO_DISPLAY_ABB")
#define VIDEOS_CTXPOP_MENU_MOVE_TO_PRIVATE				VIDEOS_GET_STR("IDS_GALLERY_OPT_MOVE_TO_PRIVATE")
#define VIDEOS_CTXPOP_MENU_REMOVE_FROM_PRIVATE			VIDEOS_GET_STR("IDS_GALLERY_OPT_REMOVE_FROM_PRIVATE")

//	Delete popup	//
#define VIDEOS_DELETEPOP_HEADER_DELETE					VIDEOS_GET_STR("IDS_VIDEO_BUTTON_DELETE")
#define VIDEOS_DELETEPOP_BUTTON_DELETE					VIDEOS_GET_STR("IDS_VIDEO_BUTTON_DELETE")
#define VIDEOS_DELETEPOP_BUTTON_DELETE_ALL				VIDEOS_GET_STR("IDS_ST_OPT_DELETE_ALL")
#define VIDEOS_DELETEPOP_MSG_PD_VIDEOS_WILL_BE_DELETED		VIDEOS_GET_STR_FMT("IDS_VIDEO_POP_PD_VIDEOS_WILL_BE_DELETED")
#define VIDEOS_DELETEPOP_MSG_ONE_VIDEO_WILL_BE_DELETED	VIDEOS_GET_STR("IDS_VIDEO_POP_1_VIDEO_WILL_BE_DELETED")
#define VIDEOS_DELETEPOP_MSG_ALL_VIDEOS_WILL_BE_DELETED	VIDEOS_GET_STR("IDS_VIDEO_POP_ALL_VIDEOS_WILL_BE_DELETED")
#define VIDEOS_DELETEPOP_MSG_ONE_FOLDER_WILL_BE_DELETED	VIDEOS_GET_STR("IDS_MUSIC_POP_1_FOLDER_WILL_BE_DELETED")
#define VIDEOS_DELETEPOP_MSG_ONE_FOLDER_WILL_BE_DELETED_IDS	("IDS_MUSIC_POP_1_FOLDER_WILL_BE_DELETED")
#define VIDEOS_DELETEPOP_MSG_THIS_FOLDER_WILL_BE_DELETED_IDS	VIDEOS_GET_STR("IDS_VIDEO_POP_THIS_FOLDER_WILL_BE_DELETED")
#define VIDEOS_DELETEPOP_MSG_PD_FOLDERS_WILL_BE_DELETED	VIDEOS_GET_STR_FMT("IDS_VIDEO_POP_PD_FOLDERS_WILL_BE_DELETED")
#define VIDEOS_DELETEPOP_MSG_ALL_FOLDERS_WILL_BE_DELETED	VIDEOS_GET_STR("IDS_VIDEO_POP_ALL_FOLDERS_WILL_BE_DELETED")
#define VIDEOS_DELETEPOP_MSG_DELETING					VIDEOS_GET_STR("IDS_VIDEO_TPOP_DELETING_ING")
#define VIDEOS_DELETEPOP_MSG_DELETING_IDS				("IDS_VIDEO_TPOP_DELETING_ING")
#define VIDEOS_DELETEPOP_HEADER_DELETE_VIDEO			VIDEOS_GET_STR("IDS_VIDEO_HEADER_DELETE_VIDEO")	// not be used in lite
#define VIDEOS_DELETEPOP_HEADER_DELETE_VIDEOS			VIDEOS_GET_STR("IDS_VIDEO_HEADER_DELETE_VIDEOS")	// not be used in lite
#define MP_COM_POP_DELETED								(dgettext(MP_SYS_STRING, "IDS_COM_POP_DELETED"))	// not be used in lite

//	Rename popup	//
#define VIDEOS_RENAMEPOP_HEADER_RENAME					VIDEOS_GET_STR("IDS_VIDEO_OPT_RENAME")
#define VIDEOS_RENAMEPOP_HEADER_RENAME_IDS				("IDS_VIDEO_OPT_RENAME")
#define VIDEOS_RENAMEPOP_BUTTON_RENAME					VIDEOS_GET_STR("IDS_VIDEO_OPT_RENAME")
#define VIDEOS_RENAMEPOP_BUTTON_RENAME_IDS				("IDS_VIDEO_OPT_RENAME")

//	View as popup	//
#define VIDEOS_VIEWASPOP_HEADER_VIEW_AS					VIDEOS_GET_STR("IDS_VIDEO_OPT_VIEW_AS")
#define VIDEOS_VIEWASPOP_HEADER_VIEW_AS_IDS				("IDS_VIDEO_OPT_VIEW_AS")

//	Sort by popup		//
#define VIDEOS_SORTBYPOP_HEADER_SORT_BY					VIDEOS_GET_STR("IDS_VIDEO_OPT_SORT_BY")
#define VIDEOS_SORTBYPOP_HEADER_SORT_BY_IDS				("IDS_VIDEO_OPT_SORT_BY")

//	Download popup	//
#define VIDEOS_DOWNLOADPOP_MSG_1_VIDEO_WILL_BE_DOWNLOADED	"1 video will be downloaded."	// TODO. need to change STMS string after release new ID
#define VIDEOS_DOWNLOADPOP_MSG_PD_VIDEOS_WILL_BE_DOWNLOADED "%d videos will be downloaded."	// TODO. need to change STMS string after release new ID
#define VIDEOS_DOWNLOADPOP_MSG_ALL_VIDEOS_WILL_BE_DOWNLOADED "All videos will be downloaded."	// TODO. need to change STMS string after release new ID
#define VIDEOS_DOWNLOADPOP_BUTTON_DOWNLOAD			VIDEOS_GET_STR("IDS_VIDEO_BUTTON_DOWNLOAD")

//	Move popup (not be used for lite)	//
#define MP_PERSONAL_ITEM_MOVE_TO							VIDEOS_GET_STR_FMT("IDS_VIDEO_POP_THE_SELECTED_ITEM_WILL_BE_MOVED_TO_PS")
#define MP_PERSONAL_ITEMS_MOVE_TO						VIDEOS_GET_STR_FMT("IDS_VIDEO_POP_THE_SELECTED_ITEMS_WILL_BE_MOVED_TO_PS")
#define MP_PERSONAL_DONT_ASK_AGAIN						VIDEOS_GET_STR("IDS_MUSIC_BUTTON_DONT_ASK_AGAIN")
#define MP_TEXT_MOVING_IDS									("IDS_VIDEO_POP_MOVING_ING")
#define MP_TEXT_MOVING										VIDEOS_GET_STR("IDS_VIDEO_POP_MOVING_ING")
#define MP_TEXT_REMOVING_IDS								("IDS_VIDEO_POP_REMOVING_ING")
#define MP_BUTTON_MOVE_IDS								("IDS_VIDEO_BUTTON_MOVE_ABB")
#define MP_COM_OPT_ADDED									(dgettext(MP_SYS_STRING, "IDS_COM_OPT_ADDED"))	// status bar noti
#define MP_COM_OPT_UNABLE_ADDED							(dgettext(MP_SYS_STRING, "IDS_COM_BODY_UNABLE_TO_ADD"))	// status bar noti
#define MP_COM_BODY_MOVE									(dgettext(MP_SYS_STRING, "IDS_COM_BODY_MOVE"))

//	Share panel (not used at lite)	//
#define MP_SHARE_BLUETOOTH								(dgettext(MP_SYS_STRING, "IDS_COM_BODY_BLUETOOTH"))
#define MP_SHARE_FTM										(dgettext(MP_SYS_STRING, "IDS_COM_OPT1_WI_FI_DIRECT"))
#define MP_SHARE_MESSAGE							 		VIDEOS_GET_STR("IDS_VIDEO_OPT_MESSAGE_ABB")
#define MP_SHARE_EMAIL										VIDEOS_GET_STR("IDS_VIDEO_OPT_EMAIL_ABB")

//	Notificatioin msg (noti, toast popup)	//
#define VIDEOS_NOTIPOP_MSG_ALREADY_EXISTS				VIDEOS_GET_STR("IDS_VIDEO_TPOP_FILE_NAME_ALREADY_IN_USE")
#define VIDEOS_NOTIPOP_MSG_ALREADY_EXISTS_IDS			("IDS_VIDEO_TPOP_FILE_NAME_ALREADY_IN_USE")
#define VIDEOS_NOTIPOP_MSG_SHARE_ITEM_MAX				VIDEOS_GET_STR_FMT("IDS_VIDEO_TPOP_MAXIMUM_NUMBER_OF_ATTACHMENTS_HPD_EXCEEDED")
#define VIDEOS_NOTIPOP_MSG_UNABLE_TO_PLAY_THIS_VIDEO_SIDESYNC		VIDEOS_GET_STR("IDS_VIDEO_POP_UNABLE_TO_PLAY_THIS_VIDEO_WHILE_USING_SIDESYNC")
#define VIDEOS_NOTIPOP_MSG_INVALID_CHARACTERS 			VIDEOS_GET_STR("IDS_SWALL_HEADER_INVALID_CHARACTER")
#define VIDEOS_NOTIPOP_MSG_MAX_NUM_OF_CHARACTERS		dgettext(MP_SYS_STRING, "IDS_COM_POP_MAXIMUM_NUMBER_OF_CHARACTERS_REACHED")
#define VIDEOS_NOTIPOP_MSG_CONNECTION_FAIL				(dgettext(MP_SYS_STRING, "IDS_COM_POP_CONNECTION_ERROR"))
#define VIDEOS_NOTIPOP_MSG_FILE_NOT_EXIST				(dgettext(MP_SYS_STRING, "IDS_COM_POP_FILE_NOT_EXIST"))
#define VIDEOS_NOTIPOP_MSG_UNABLE_TO_SHARE_DRM_FILE	VIDEOS_GET_STR("IDS_MUSIC_POP_UNABLE_TO_SHARE_DRM_FILE")	// it will be removed.	// not be used for lite
#define VIDEOS_NOTIPOP_MSG_UNABLE_TO_PLAY_VIDEO_DURING_CALL 	VIDEOS_GET_STR("IDS_VPL_BODY_UNABLE_TO_PLAY_VIDEO_DURING_CALL")
#define VIDEOS_NOTIPOP_MSG_TURN_PHONE_OVER_TO_MUTE_IDS		("IDS_VPL_BODY_TURN_PHONE_OVER_TO_MUTE_INCOMING_CALLS_MESSAGE_ALERTS_AND_ALARMS")
#define VIDEOS_NOTIPOP_MSG_CLOUD_FILE_CONNECT_FAIL				("IDS_VIDEO_POP_THIS_FILE_IS_UNAVAILABLE_WHILE_OFFLINE_CHECK_NETWORK_CONNECTION_AND_TRY_AGAIN")
#define VIDEOS_NOTIPOP_MSG_MOVE_TO_PERSONAL_STORAGE_FAILED	VIDEOS_GET_STR("IDS_VIDEO_POP_FAILED_TO_MOVE_TO_PERSONAL_STORAGE")
#define VIDEOS_NOTIPOP_MSG_MOVE_TO_NORMAL_STORAGE_FAILED		VIDEOS_GET_STR("IDS_VIDEO_POP_FAILED_TO_MOVE_TO_NORMAL_STORAGE")

/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//	Option
/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//	Sort by	//
#define VIDEOS_SORTBYOPT_OPT_DATE_MOST_RECENT			VIDEOS_GET_STR("IDS_VIDEO_OPT_DATE_HMOST_RECENT_ABB")
#define VIDEOS_SORTBYOPT_OPT_NAME						VIDEOS_GET_STR("IDS_VIDEO_OPT_NAME_HA_Z_ABB")
#define VIDEOS_SORTBYOPT_OPT_RECENTLY_VIEWED			VIDEOS_GET_STR("IDS_VIDEO_OPT_RECENTLY_VIEWED_ABB")
#define VIDEOS_SORTBYOPT_OPT_RECENTLY_ADDED				VIDEOS_GET_STR("IDS_VIDEO_OPT_RECENTLY_ADDED_ABB")
#define VIDEOS_SORTBYOPT_OPT_TITLE						VIDEOS_GET_STR("IDS_VIDEO_OPT_TITLE")
#define VIDEOS_SORTBYOPT_OPT_SIZE							VIDEOS_GET_STR("IDS_VIDEO_OPT_SIZE")
#define VIDEOS_SORTBYOPT_OPT_TYPE							VIDEOS_GET_STR("IDS_VIDEO_OPT_TYPE")

//	Veiw as	//
#define VIDEOS_VIEWASOPT_OPT_LIST							VIDEOS_GET_STR("IDS_VIDEO_OPT_LIST")
#define VIDEOS_VIEWASOPT_OPT_THUMBNAIL					VIDEOS_GET_STR("IDS_VIDEO_OPT_VIDEOS")	// not be used for lite
#define VIDEOS_VIEWASOPT_OPT_FOLDER						VIDEOS_GET_STR("IDS_VIDEO_OPT_FOLDERS_ABB")
#define VIDEOS_TITLE_OPT_FOLDER						VIDEOS_GET_STR("IDS_VIDEO_OPT_FOLDERS_ABB")

//	Content to display	//
#define VIDEOS_CONTENTTODISPLAYOPT_OPT_ALLCONTENT		VIDEOS_GET_STR("IDS_VPL_OPT_ALL_CONTENT_ABB")
#define VIDEOS_CONTENTTODISPLAYOPT_OPT_PHONE			VIDEOS_GET_STR("IDS_VPL_OPT_CONTENT_ON_DEVICE_ABB")
#define VIDEOS_CONTENTTODISPLAYOPT_OPT_CLOUD			VIDEOS_GET_STR("IDS_VPL_OPT_CONTENT_IN_DROPBOX_ABB")

//dropbox
#define VIDEOS_POP_CLOUD_FILE_CONNECT_FAIL				("IDS_VIDEO_POP_THIS_FILE_IS_UNAVAILABLE_WHILE_OFFLINE_CHECK_NETWORK_CONNECTION_AND_TRY_AGAIN")
#define VIDEOS_VIEW_DROPBOX_NAME						VIDEOS_GET_STR("IDS_CLOUD_BODY_DROPBOX_ABB")


/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//	View
/////////////////////////////////////////////////////////////////////////////////////////////////////////////

//	Nocontent	//
#define VIDEOS_NOCONTENT_MSG_NO_VIDEOS					VIDEOS_GET_STR("IDS_VIDEO_NPBODY_NO_VIDEOS")
#define VIDEOS_NOCONTENT_MSG_NO_VIDEOS_IDS				VIDEOS_GET_STR("IDS_VIDEO_NPBODY_NO_VIDEOS")
#define VIDEOS_NOCONTENT_MSG_NO_VIDEOS_DESC			VIDEOS_GET_STR("IDS_VIDEO_BODY_AFTER_YOU_RECORD_VIDEOS_USING_THE_CAMERA_THEY_WILL_BE_SHOWN_HERE")
#define VIDEOS_NOCONTENT_MSG_NO_VIDEOS_DESC_IDS		("IDS_VIDEO_BODY_AFTER_YOU_RECORD_VIDEOS_USING_THE_CAMERA_THEY_WILL_BE_SHOWN_HERE")

//	List view		//
#define VIDEOS_LISTVIEW_BODY_ONE_VIDEO					VIDEOS_GET_STR("IDS_VPL_BODY_1_VIDEO")
#define VIDEOS_LISTVIEW_BODY_PD_VIDEOS					VIDEOS_GET_STR_FMT("IDS_VIDEO_HEADER_PD_VIDEOS")

//	Folder view	//
#define VIDEOS_FOLDERVIEW_BODY_ONE_FOLDER				VIDEOS_GET_STR("IDS_VPL_BODY_1_FOLDER")
#define VIDEOS_FOLDERVIEW_BODY_PD_FOLDERS				VIDEOS_GET_STR_FMT("IDS_VIDEO_HEADER_PD_FOLDERS")
#define VIDEOS_FOLDERVIEW_BODY_DEVICE_MEMORY			VIDEOS_GET_STR("IDS_IS_BODY_DEVICE_MEMORY_ABB")
#define VIDEOS_FOLDERVIEW_BODY_SD_CARD					VIDEOS_GET_STR("IDS_IS_BODY_SD_CARD")
#define VIDEOS_FOLDERVIEW_BODY_USB_MEMORY				VIDEOS_GET_STR("IDS_IS_BODY_SD_CARD")	// need to add IDS about USB memory

//	Folder item view	//

//	Search view	//
#define VIDEOS_SEARCHVIEW_MSG_NO_RESULTS_FOUND_IDS	("IDS_MUSIC_BODY_NO_RESULTS_FOUND")
#define VIDEOS_SEARCHVIEW_MSG_NO_SEARCH_RESULTS		VIDEOS_GET_STR("IDS_VIDEO_BODY_NO_SEARCH_RESULTS")
#define VIDEOS_SEARCHVIEW_MSG_NO_SEARCH_RESULTS_IDS	("IDS_VIDEO_BODY_NO_SEARCH_RESULTS")

//	Share view	//
#define VIDEOS_SHAREVIEW_DONE_IDS				VIDEOS_GET_STR("IDS_TPLATFORM_ACBUTTON_DONE_ABB")
#define VIDEOS_SHAREVIEW_CANCEL_IDS				VIDEOS_GET_STR("IDS_TPLATFORM_ACBUTTON_CANCEL_ABB")
//	Delete view	//
#define VIDEOS_DELETEVIEW_DELETE_IDS				VIDEOS_GET_STR("IDS_TPLATFORM_ACBUTTON_DELETE_ABB")
#define VIDEOS_DELETEVIEW_CANCEL_IDS				VIDEOS_GET_STR("IDS_TPLATFORM_ACBUTTON_CANCEL_ABB")

//	Select view	//
#define VIDEOS_SELECTVIEW_HEADER_PD_SELECTED			VIDEOS_GET_STR_FMT("IDS_VIDEO_HEADER_PD_SELECTED")
#define VIDEOS_SELECTVIEW_BODY_SELECT_ALL				VIDEOS_GET_STR_FMT("IDS_VIDEO_HEADER_SELECT_ALL")
#define VIDEOS_SELECTVIEW_BODY_SELECT_ALL_IDS			("IDS_VIDEO_HEADER_SELECT_ALL")
#define VIDEOS_SELECTVIEW_HEADER_SELECT_ITEMS			VIDEOS_GET_STR("IDS_VPL_BODY_SELECT_ITEMS")	// not be used in lite
#define VIDEOS_SELECTVIEW_HEADER_SELECT_ITEMS_IDS		("IDS_VPL_BODY_SELECT_ITEMS")	// not be used in lite
#define VIDEOS_SELECTVIEW_HEADER_SELECT					VIDEOS_GET_STR("IDS_GALLERY_HEADER_SELECT")
#define VIDEOS_SELECTVIEW_HEADER_SELECT_IDS				("IDS_GALLERY_HEADER_SELECT")
#define VIDEOS_SELECTVIEW_HEADER_SELECT_VIDEO				VIDEOS_GET_STR("IDS_GALLERY_HEADER_SELECT_VIDEO")

//	Rename view	//
#define VIDEOS_RENAMEVIEW_HEADER_RENAME				VIDEOS_GET_STR("IDS_VIDEO_OPT_RENAME")
#define VIDEOS_RENAMEVIEW_HEADER_RENAME_IDS			("IDS_VIDEO_OPT_RENAME")

//	Detail view	//
#define VIDEOS_DETAILVIEW_HEADER_DETAILS					VIDEOS_GET_STR("IDS_VIDEO_OPT_DETAILS")
#define VIDEOS_DETAILVIEW_HEADER_DETAILS_IDS				("IDS_VIDEO_OPT_DETAILS")
#define VIDEOS_DETAILVIEW_BODY_TITLE						VIDEOS_GET_STR("IDS_VIDEO_OPT_TITLE")
#define VIDEOS_DETAILVIEW_BODY_SIZE						VIDEOS_GET_STR("IDS_VIDEO_OPT_SIZE")
#define VIDEOS_DETAILVIEW_BODY_DATE						(dgettext(MP_SYS_STRING, "IDS_COM_BODY_DATE" ))
#define VIDEOS_DETAILVIEW_BODY_FORMAT					VIDEOS_GET_STR("IDS_VPL_OPT_FORMAT")
#define VIDEOS_DETAILVIEW_BODY_RESOLUTION				VIDEOS_GET_STR("IDS_VIDEO_BODY_RESOLUTION")
#define VIDEOS_DETAILVIEW_BODY_LAST_MODIFIED			("Last modified")
#define VIDEOS_DETAILVIEW_BODY_LOCATION					(dgettext(MP_SYS_STRING, "IDS_COM_BODY_LOCATION"))
#define VIDEOS_DETAILVIEW_BODY_LATITUDE					VIDEOS_GET_STR("IDS_VIDEO_BODY_LATITUDE")
#define VIDEOS_DETAILVIEW_BODY_LONGITUDE					VIDEOS_GET_STR("IDS_VIDEO_BODY_LONGITUDE")
#define VIDEOS_DETAILVIEW_BODY_UNKNOWN					("Unknown")
#define VIDEOS_DETAILVIEW_BODY_KB							(dgettext(MP_SYS_STRING, "IDS_COM_BODY_KB"))
#define VIDEOS_DETAILVIEW_BODY_B							(dgettext(MP_SYS_STRING, "IDS_COM_BODY_B"))
#define VIDEOS_DETAILVIEW_BODY_MB						(dgettext(MP_SYS_STRING, "IDS_COM_BODY_MB"))
#define VIDEOS_DETAILVIEW_BODY_GB						(dgettext(MP_SYS_STRING, "IDS_COM_BODY_GB"))

//	Device view	//	// not be used in lite
#define VP_TEXT_NOT_TO_CONNECT_WIFI_IDS					("IDS_IS_BODY_YOU_NEED_TO_BE_CONNECTED_TO_A_WI_FI_NETWORK_TO_SCAN_FOR_NEARBY_DEVICES_CONNECT_VIA_WI_FI_AND_TRY_AGAIN")
#define VP_TEXT_NO_DEVICE_FOUND_IDS						("IDS_IS_BODY_NO_DEVICES_FOUND_ENABLE_THE_SHARE_CONTENT_FUNCTION_ON_YOUR_NEARBY_DEVICES")
#define MP_VPL_LIST_CTX_NEAR_BY_DEVICE					VIDEOS_GET_STR("IDS_VIDEO_OPT_NEARBY_DEVICES_ABB")
#define MP_VPL_LIST_CTX_NEAR_BY_DEVICE_IDS				("IDS_VIDEO_OPT_NEARBY_DEVICES_ABB")
#define VS_TEXT_DISCONNECT_DEVICE							VIDEOS_GET_STR_FMT("IDS_DLNA_POP_DISCONNECTED_FROM_PS_CHECK_THE_NETWORK_STATUS_AND_THE_CONNECTED_DEVICE")
#define MP_COM_SK_REFRESH									(dgettext(MP_SYS_STRING, "IDS_COM_SK_REFRESH"))
#define VS_TEXT_SETTINGS_DEVICES_IDS 						("IDS_IS_BODY_DEVICES")
#define VS_TEXT_LOADING									VIDEOS_GET_STR("IDS_IS_BODY_LOADING_ING")
#define MP_VPL_DEVICES										VIDEOS_GET_STR_FMT("IDS_MUSIC_HEADER_PD_DEVICES")
#define MP_VPL_CTX_SCAN_NEAR_BY_DEVICE_IDS				("IDS_VIDEO_OPT_SCAN_FOR_NEARBY_DEVICES")
#define MP_TEXT_NO_DEVICES_IDS							("IDS_VIDEO_BODY_NO_DEVICES")

//	Cloud view	//
#define MP_COM_POP_DOWNLOADED							(dgettext(MP_SYS_STRING, "IDS_COM_BODY_DOWNLOADED"))
#define MP_VPL_DOWNLOAD_LIST_NO_VIDEO					VIDEOS_GET_STR("IDS_VPL_POP_YOU_CAN_DOWNLOAD_AND_ENJOY_VIDEOS_THROUGH_THE_VIDEO_STORE")
#define MP_VPL_DOWNLOAD_LIST_NO_VIDEO_IDS				("IDS_VPL_POP_YOU_CAN_DOWNLOAD_AND_ENJOY_VIDEOS_THROUGH_THE_VIDEO_STORE")
#define MP_DOWNLOAD_STR_SELECT_QUALITY 					VIDEOS_GET_STR("IDS_VIDEO_HEADER_SELECT_QUALITY_ABB")

//	Tab (Personal, Devices)	//	// not be used in lite
#define MP_VPL_LIST_TAB_PERSONAL							VIDEOS_GET_STR("IDS_IS_TAB4_PERSONAL_M_CONTENT")
#define MP_VPL_LIST_TAB_PERSONAL_IDS						("IDS_IS_TAB4_PERSONAL_M_CONTENT")
#define MP_VPL_LIST_TAB_VIEW								VIDEOS_GET_STR("IDS_VIDEO_BUTTON_VIEW")


/////////////////////////////////////////////////////////////////////////////////////////////////////////////
//	Other strings
/////////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifdef ENABLE_DRM_FEATURE
//	DRM feature string	//
#define MP_VPL_DRM_PS_1_MORE_TIME_START_NOW_Q			(dgettext(MP_SYS_STRING, "IDS_COM_POP_YOU_CAN_USE_PS_1_MORE_TIME_START_NOW_Q"))
#define MP_VPL_DRM_PS_2_MORE_TIME_START_NOW_Q			(dgettext(MP_SYS_STRING, "IDS_COM_POP_YOU_CAN_USE_PS_2_MORE_TIMES_START_NOW_Q"))
#define MP_VPL_DRM_PS_FOR_PD_DAYS_START_NOW_Q			(dgettext(MP_SYS_STRING, "IDS_COM_POP_YOU_CAN_USE_PS_FOR_PD_DAYS_START_NOW_Q"))
#define MP_VPL_DRM_PS_CURRENTLY_LOCKED_UNLOCK_Q		(dgettext(MP_SYS_STRING, "IDS_COM_POP_PS_CURRENTLY_LOCKED_UNLOCK_Q"))
#define MP_VPL_DRM_PS_CAN_USE_1_MORE_TIME_GET_ANOTHER_LICENCE_Q	(dgettext(MP_SYS_STRING, "IDS_COM_POP_YOU_CAN_USE_PS_1_MORE_TIME_GET_ANOTHER_LICENCE_Q"))
#define MP_VPL_DRM_PS_CANNOT_USE_ANY_MORE_TIMES_GET_ANOTHER_LICENCE_Q	(dgettext(MP_SYS_STRING, "IDS_COM_POP_YOU_CANNOT_USE_PS_ANY_MORE_TIMES_GET_ANOTHER_LICENCE_Q"))
#define MP_VPL_DRM_PS_IS_ABOUT_TO_EXPIRE_GET_ANOTHER_LICENCE_Q	(dgettext(MP_SYS_STRING, "IDS_COM_POP_PS_IS_ABOUT_TO_EXPIRE_GET_ANOTHER_LICENCE_Q"))
#endif

//	Sensor Control (not be used in lite)	//
#define MP_VPL_ENABLE_MOTION_IDS							("IDS_MUSIC_BUTTON_ENABLE_MOTION")


#endif //_VIDEO_STRING_DEFINE_
